/* ============================================================================
 * audio.js  —  Handspan Game audio engine
 * ----------------------------------------------------------------------------
 * Strategy:
 *   1. Try to load real audio files from assets/audios/ (mapped by name).
 *   2. If a file is missing / cannot decode, fall back to a tiny WebAudio
 *      synthesizer so the game ALWAYS has tactile sound — never silent,
 *      never throwing.
 *
 * Public API (all safe to call any time, before or after unlock):
 *   HS.Audio.unlock()        -> resume context (call on first user gesture)
 *   HS.Audio.playClick()
 *   HS.Audio.playPop()
 *   HS.Audio.playHover()
 *   HS.Audio.playSuccess()
 *   HS.Audio.playWrong()
 *   HS.Audio.playWhoosh()
 *   HS.Audio.playSparkle()
 *   HS.Audio.playDialogue()
 *   HS.Audio.playVO(text)    -> speak the recorded Gogo/Tara line for an
 *                               on-screen text box (SFX duck underneath)
 *   HS.Audio.playBgm()       -> (re)start the looping music bed; unlock()
 *                               already calls it, so the bed runs on its own
 * ========================================================================== */
window.HS = window.HS || {};

HS.Audio = (function () {
  'use strict';

  // No WebAudio sample files: every UI SFX is generated by the tiny synth below.
  // The real audio assets are Ogg files played through <audio> elements (so they
  // work on file:// too): the hand-place drop (assets/handPlaceSound.ogg), the
  // lights-on swell (assets/LighsOn.ogg) and the success clap (assets/clapSound.ogg).
  var FILES = {};

  var ctx = null;          // shared AudioContext (created lazily on unlock)
  var master = null;       // master gain
  var buffers = {};        // decoded file buffers, keyed by sound name
  var unlocked = false;
  var muted = false;

  /* ---- context lifecycle ------------------------------------------------ */
  function ensureCtx() {
    if (ctx) return ctx;
    try {
      var AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      ctx = new AC();
      master = ctx.createGain();
      master.gain.value = 0.9;
      master.connect(ctx.destination);
    } catch (e) {
      ctx = null;
    }
    return ctx;
  }

  function unlock() {
    if (unlocked) return;
    var c = ensureCtx();
    if (!c) return;
    if (c.state === 'suspended') c.resume();
    // Play a near-silent blip to satisfy mobile autoplay policies.
    try {
      var o = c.createOscillator();
      var g = c.createGain();
      g.gain.value = 0.0001;
      o.connect(g); g.connect(master);
      o.start(); o.stop(c.currentTime + 0.02);
    } catch (e) { /* no-op */ }
    unlocked = true;
    loadFiles();  // attempt (and fail gracefully) to fetch real audio
    preloadVO();  // warm the Gogo/Tara voice lines
    playBgm();    // start the music bed while still inside the user gesture
  }

  /* ---- optional file loading (best-effort) ------------------------------ */
  function loadFiles() {
    var c = ensureCtx();
    if (!c || typeof fetch !== 'function') return;
    Object.keys(FILES).forEach(function (name) {
      fetch(FILES[name])
        .then(function (r) { if (!r.ok) throw 0; return r.arrayBuffer(); })
        .then(function (buf) {
          return new Promise(function (res, rej) {
            c.decodeAudioData(buf, res, rej);
          });
        })
        .then(function (decoded) { buffers[name] = decoded; })
        .catch(function () { /* graceful: keep synth fallback */ });
    });
  }

  function playBuffer(name) {
    var c = ensureCtx();
    if (!c || !buffers[name]) return false;
    var src = c.createBufferSource();
    src.buffer = buffers[name];
    src.connect(master);
    src.start();
    return true;
  }

  /* ---- low-level synth helpers ------------------------------------------ */
  // A single shaped oscillator note.
  function note(opts) {
    var c = ensureCtx();
    if (!c || muted) return;
    var t0 = c.currentTime + (opts.delay || 0);
    var osc = c.createOscillator();
    var gain = c.createGain();
    osc.type = opts.type || 'sine';
    osc.frequency.setValueAtTime(opts.f0, t0);
    if (opts.f1 != null) {
      osc.frequency.exponentialRampToValueAtTime(Math.max(1, opts.f1), t0 + opts.dur);
    }
    var peak = opts.gain == null ? 0.25 : opts.gain;
    gain.gain.setValueAtTime(0.0001, t0);
    gain.gain.exponentialRampToValueAtTime(peak, t0 + 0.012);
    gain.gain.exponentialRampToValueAtTime(0.0001, t0 + opts.dur);
    osc.connect(gain); gain.connect(master);
    osc.start(t0);
    osc.stop(t0 + opts.dur + 0.02);
  }

  // Filtered noise burst (used for whoosh / sparkle shimmer).
  function noise(opts) {
    var c = ensureCtx();
    if (!c || muted) return;
    var t0 = c.currentTime + (opts.delay || 0);
    var len = Math.floor(c.sampleRate * opts.dur);
    var buf = c.createBuffer(1, len, c.sampleRate);
    var data = buf.getChannelData(0);
    for (var i = 0; i < len; i++) data[i] = (Math.random() * 2 - 1);
    var src = c.createBufferSource();
    src.buffer = buf;
    var filt = c.createBiquadFilter();
    filt.type = opts.filter || 'bandpass';
    filt.frequency.setValueAtTime(opts.fStart, t0);
    filt.frequency.exponentialRampToValueAtTime(Math.max(80, opts.fEnd), t0 + opts.dur);
    filt.Q.value = opts.q || 0.8;
    var gain = c.createGain();
    var peak = opts.gain == null ? 0.18 : opts.gain;
    gain.gain.setValueAtTime(0.0001, t0);
    gain.gain.exponentialRampToValueAtTime(peak, t0 + 0.02);
    gain.gain.exponentialRampToValueAtTime(0.0001, t0 + opts.dur);
    src.connect(filt); filt.connect(gain); gain.connect(master);
    src.start(t0); src.stop(t0 + opts.dur + 0.02);
  }

  /* ---- public sound effects --------------------------------------------- */
  function playClick() {
    if (playBuffer('click')) return;
    note({ type: 'triangle', f0: 540, f1: 720, dur: 0.09, gain: 0.22 });
  }

  function playPop() {
    if (playBuffer('pop')) return;
    note({ type: 'sine', f0: 320, f1: 760, dur: 0.12, gain: 0.28 });
  }

  function playHover() {
    if (playBuffer('hover')) return;
    note({ type: 'sine', f0: 880, f1: 1040, dur: 0.06, gain: 0.10 });
  }

  function playSuccess() {
    if (playBuffer('success')) return;
    // Happy ascending arpeggio (C-E-G-C).
    var seq = [523.25, 659.25, 783.99, 1046.5];
    seq.forEach(function (f, i) {
      note({ type: 'triangle', f0: f, dur: 0.22, gain: 0.26, delay: i * 0.10 });
    });
    noise({ filter: 'highpass', fStart: 4000, fEnd: 9000, dur: 0.5, gain: 0.05, delay: 0.2 });
  }

  function playWrong() {
    if (playBuffer('wrong')) return;
    // Gentle (kid-friendly) descending "uh-oh", never harsh.
    note({ type: 'sine', f0: 380, f1: 300, dur: 0.16, gain: 0.22 });
    note({ type: 'sine', f0: 300, f1: 220, dur: 0.22, gain: 0.22, delay: 0.16 });
  }

  function playWhoosh() {
    if (playBuffer('whoosh')) return;
    // soft descending "swoop" for moving pieces (NOT a harsh noise/clap burst)
    note({ type: 'sine', f0: 620, f1: 280, dur: 0.26, gain: 0.09 });
    noise({ filter: 'lowpass', fStart: 520, fEnd: 180, dur: 0.20, q: 0.3, gain: 0.03 });
  }

  function playSparkle() {
    if (playBuffer('sparkle')) return;
    [1320, 1760, 2090].forEach(function (f, i) {
      note({ type: 'sine', f0: f, f1: f * 1.5, dur: 0.14, gain: 0.10, delay: i * 0.05 });
    });
  }

  function playDialogue() {
    if (playBuffer('dialogue')) return;
    // Soft "blip" used when a speech bubble appears.
    note({ type: 'sine', f0: 600, f1: 520, dur: 0.10, gain: 0.12 });
  }

  /* ---- VOICE-OVERS (Gogo + Tara) ----------------------------------------
   * Recorded lines live in audios/Gogo + audios/Tara. Every text box calls
   * playVO(<its exact on-screen text>); the map below normalizes the text
   * (lowercase, punctuation stripped) and picks the file. Rules:
   *   - one voice at a time: a new VO cuts the previous one off
   *   - while a voice speaks, EVERY SFX channel is DUCKED (the synth master
   *     bus and the ogg <audio> effects) so the voice never fights the
   *     clap / celebrate chime / wrong-buzz firing on the same beat; the
   *     levels restore the moment the line ends
   *   - array entries are alternate takes, cycled so a repeated line
   *     ("Here?", "No!") doesn't sound like a stuck record
   *   - an unmapped line falls back to the old dialogue blip, so a missing
   *     recording never leaves a bubble silent */
  var VO_DUCK = 0.22;      // synth master gain while a voice is speaking
  var VO_DUCK_EL = 0.25;   // ogg <audio> SFX volume while a voice is speaking
  var SFX_VOL = 0.9;       // normal level for both, restored after the line
  function voKey(text) {
    return String(text).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  }
  var G = 'audios/Gogo/', T = 'audios/Tara/';
  var VO_FILES = {
    /* --- intro + tutorial showcase --- */
    'welcome to the hall of helpful things': G + 'Welcome to the hall of helpful things.ogg',
    'here are the tables': G + 'Here are the tables.ogg',
    'let us measure how long each table is': G + 'Let us measure how long each table is.ogg',
    'tap to select this table': G + 'Tap to select this table.ogg',
    /* --- guided drag lesson --- */
    'we need to measure the table using handspans': G + 'We need to measure the table using handspans.ogg',
    'but how': G + 'but how.ogg',
    'let us drag the first handspan': G + 'Let us drag the first handspan.ogg',
    'here': [G + 'here.ogg', G + 'heree.ogg'],
    'no': [G + 'no.ogg', G + 'noo.ogg'],
    'we must start from one end of the table': G + 'We must start from one end of the table.ogg',
    'let us drag the next handspan': G + 'Let us drag the next handspan.ogg',
    // trimmed from the "No! ..." master takes (leading "No" cut — the "No!"
    // bubble right before each rule line already speaks its own no.ogg)
    'handspans must not overlap': G + 'Handspans must not overlap.ogg',
    'then can we keep it here': [G + 'Then can we keep it here.ogg', G + 'Then can we keep it heree.ogg'],
    // cropped from the "Then can we keep it here" takes (leading "Then" cut)
    'can we keep it here': [G + 'Can we keep it here.ogg', G + 'Can we keep it heree.ogg'],
    'there must be no gap between two handspans': G + 'There must be no gap between two handspans.ogg',
    // the "Yes That is the perfect way" recording is SPLIT in two, matching
    // the two on-screen bubbles ("Yes!" -> "That is the perfect way.")
    'yes': G + 'Yes.ogg',
    'that is the perfect way': G + 'That is the perfect way.ogg',
    'no gaps no overlaps': G + 'No Gaps No Overlaps.ogg',
    'now you try': G + 'Now you try.ogg',
    'drag the rest with no gaps': G + 'Drag the rest with no gaps.ogg',
    /* --- task panels --- */
    'measure how long the table is': G + 'Measure how long the table is.ogg',
    'measure how tall the candle is': G + 'Measure how tall the candle is.ogg',
    'guess how tall the candle stand is': G + 'Guess how tall the candle stand is.ogg',
    'guess how long the tablecloth is': G + 'Guess how long the tablecloth is.ogg',
    /* --- success / wrong / clue feedback --- */
    'well done': G + 'Well done.ogg',
    'hurray': G + 'Hooray.ogg',
    'let us try again': G + 'let us try again.ogg',
    'here is a clue': G + 'here is a clue.ogg',
    'the table is 5 handspans long': G + 'The table is 5 handspans long.ogg',
    'the table is 6 handspans long': G + 'The table is 6 handspans long.ogg',
    'the table is 8 handspans long': G + 'The table is 8 handspans long.ogg',
    'the candle is 2 handspans tall': G + 'The candle is 2 handspans tall.ogg',
    'the candle is 3 handspans tall': G + 'The candle is 3 handspans tall.ogg',
    'the candle is 4 handspans tall': G + 'The candle is 4 handspans tall.ogg',
    'the candle stand is 3 handspans tall': G + 'The candle stand is 3 handspans tall.ogg',
    'the candle stand is 5 handspans tall': G + 'The candle stand is 5 handspans tall.ogg',
    'the candle stand is 6 handspans tall': G + 'The candle stand is 6 handspans tall.ogg',
    'the cloth is 7 handspans long': G + 'The tablecloth is 7 handspans long.ogg',
    'the cloth is 8 handspans long': G + 'The tablecloth is 8 handspans long.ogg',
    'the cloth is 10 handspans long': G + 'The tablecloth is 10 handspans long.ogg',
    /* --- flow intros --- */
    'here are the candles': G + 'Here are the candles.ogg',
    'here are the candle stands': G + 'Here are the candle stands.ogg',
    'let us measure how tall each candle stand is': G + 'Let us measure how tall each candle stand is.ogg',
    'let us measure how tall each candle is': G + 'Let us measure how tall each candle is.ogg',
    'here are the tablecloths': G + 'Here are the tablecloths.ogg',
    'let us measure how long each tablecloth is': G + 'Let us measure how long each tablecloth is.ogg',
    /* --- finale story (Tara) + end screen --- */
    'we need a table that is 6 handspans long': T + 'We need a table that is 6 handspans long.ogg',
    'we need a candle that is 3 handspans tall': T + 'We need a candle that is 3 handspans tall.ogg',
    'we need a candle stand that is 5 handspans tall': T + 'We need a candle stand that is 5 handspans tall.ogg',
    'we need a tablecloth that is 8 handspans long': T + 'We need a tablecloth that is 8 handspans long.ogg',
    'you did it': G + 'Yay! You did it!.ogg'
  };
  var voCache = {};      // file -> <audio> element
  var voTakes = {};      // key -> next alternate-take index
  var voCurrent = null;  // the <audio> element speaking right now

  function voEl(file) {
    var a = voCache[file];
    if (!a) {
      a = new Audio(file);
      a.preload = 'auto';
      voCache[file] = a;
    }
    return a;
  }
  // Which file a line will use RIGHT NOW — peek only, does not advance the
  // alternate-take cursor (playVO does that). '' when the line has no recording.
  function voFileFor(text) {
    var entry = VO_FILES[voKey(text)];
    if (!entry) return '';
    if (Array.isArray(entry)) return entry[(voTakes[voKey(text)] || 0) % entry.length];
    return entry;
  }
  // Resolve once the line is decoded enough to start instantly (or a short
  // safety timeout). Callers use this to reveal a text panel IN STEP with the
  // voice — no first-line lag — without ever hanging the game on a slow file.
  function whenReady(text) {
    var file = voFileFor(text);
    if (!file) return Promise.resolve();
    var a = voEl(file);
    if (a.readyState >= 3) return Promise.resolve();   // HAVE_FUTURE_DATA: good to go
    return new Promise(function (resolve) {
      var done = false;
      function ok() {
        if (done) return; done = true;
        a.removeEventListener('canplaythrough', ok);
        a.removeEventListener('canplay', ok);
        a.removeEventListener('loadeddata', ok);
        a.removeEventListener('error', ok);
        resolve();
      }
      a.addEventListener('canplaythrough', ok);
      a.addEventListener('canplay', ok);
      a.addEventListener('loadeddata', ok);
      a.addEventListener('error', ok);
      try { a.load(); } catch (e) { /* no-op */ }
      setTimeout(ok, 1500);   // safety: never block the intro on a stubborn decode
    });
  }
  // Decoded length (seconds) of the line a text will speak, or 0 if unknown /
  // not yet loaded. Used to pace an on-screen word reveal to the voice.
  function voDuration(text) {
    var file = voFileFor(text);
    if (!file) return 0;
    var a = voEl(file);
    return (isFinite(a.duration) && a.duration > 0) ? a.duration : 0;
  }
  function voActive() { return !!(voCurrent && !voCurrent.paused && !voCurrent.ended); }
  // Resolve once no voice line is speaking (or after a safety cap). Lets a
  // caller start a NEW line without cutting one that is still finishing — e.g.
  // the finale waits for Gogo's success line to end before Tara reads her line,
  // instead of chopping it off (which sounded like the line was replayed).
  function whenVOIdle(maxWaitMs) {
    if (!voActive()) return Promise.resolve();
    var a = voCurrent;
    return new Promise(function (resolve) {
      var done = false;
      function ok() {
        if (done) return; done = true;
        a.removeEventListener('ended', ok);
        a.removeEventListener('error', ok);
        a.removeEventListener('pause', ok);
        resolve();
      }
      a.addEventListener('ended', ok);
      a.addEventListener('error', ok);
      a.addEventListener('pause', ok);   // also fires if something else cuts it
      setTimeout(ok, maxWaitMs || 5000);
    });
  }
  // duck / restore every SFX channel under the voice (live elements too)
  function duckSFX(on) {
    if (master && ctx) master.gain.setTargetAtTime(on ? VO_DUCK : SFX_VOL, ctx.currentTime, 0.05);
    [lightsOnEl, handPlaceEl, clapEl].forEach(function (a) { if (a) a.volume = on ? VO_DUCK_EL : SFX_VOL; });
    if (bgmEl) bgmEl.volume = on ? BGM_DUCK : BGM_VOL;
  }
  function sfxLevel() { return voActive() ? VO_DUCK_EL : SFX_VOL; }
  function voDone() { if (!voActive()) duckSFX(false); }
  // playVO returns a Promise that RESOLVES WHEN THE LINE FINISHES (ends, errors,
  // or is cut off by a newer VO). Callers that must stay in step with the voice
  // (e.g. the welcome panel) await this instead of guessing with a fixed timer,
  // so the text and the voice can never drift apart or get cut mid-sentence.
  function playVO(text) {
    if (muted) return Promise.resolve();
    var key = voKey(text);
    var entry = VO_FILES[key];
    if (!entry) { playDialogue(); return Promise.resolve(); }   // no recording: keep the old cue
    var file = entry;
    if (Array.isArray(entry)) {
      var t = voTakes[key] || 0;
      file = entry[t % entry.length];
      voTakes[key] = t + 1;
    }
    // The returned promise is GUARANTEED to settle exactly once — on natural
    // end, on error, when a newer line cuts this one (pause), when play() is
    // rejected, or via a hard duration-based safety net. A caller awaiting this
    // (the welcome panel) can therefore never get stuck on a silent frame.
    return new Promise(function (resolve) {
      var a, guard, settled = false;
      function finish() {
        if (settled) return;
        settled = true;
        if (guard) clearTimeout(guard);
        if (a) {
          a.removeEventListener('ended', finish);
          a.removeEventListener('error', finish);
          a.removeEventListener('pause', finish);
        }
        resolve();
      }
      try {
        if (voCurrent) { voCurrent.pause(); voCurrent.currentTime = 0; }
        a = voEl(file);
        if (!a._voWired) {
          a._voWired = true;
          a.addEventListener('ended', voDone);
          a.addEventListener('error', voDone);
          a.addEventListener('pause', voDone);   // covers being cut off by a newer VO
        }
        a.addEventListener('ended', finish);
        a.addEventListener('error', finish);
        a.addEventListener('pause', finish);     // resolves if a newer line cuts this one
        a.currentTime = 0;
        a.volume = 1;
        voCurrent = a;
        duckSFX(true);
        var p = a.play();
        if (p && p.catch) p.catch(function () { playDialogue(); voDone(); finish(); });
        // hard safety net: settle even if no media event ever fires
        var dur = (isFinite(a.duration) && a.duration > 0) ? a.duration : 8;
        guard = setTimeout(finish, (dur + 1.5) * 1000);
      } catch (e) { playDialogue(); voDone(); finish(); }
    });
  }
  // warm the VO cache once audio is unlocked so the first line has no lag
  function preloadVO() {
    Object.keys(VO_FILES).forEach(function (k) {
      var v = VO_FILES[k];
      (Array.isArray(v) ? v : [v]).forEach(function (f) { try { voEl(f); } catch (e) { /* no-op */ } });
    });
  }

  // Bag-burst for the transition screen: a low "whoomph" impact, an airy poof,
  // and a bright ascending magic sparkle as the gifts + light fly out.
  function playBurst() {
    if (playBuffer('burst')) return;
    // low boom impact
    note({ type: 'sine', f0: 190, f1: 55, dur: 0.5, gain: 0.30 });
    note({ type: 'triangle', f0: 95, f1: 40, dur: 0.42, gain: 0.16 });
    // airy "poof" of the bag opening
    noise({ filter: 'bandpass', fStart: 900, fEnd: 220, dur: 0.38, q: 0.6, gain: 0.14 });
    noise({ filter: 'highpass', fStart: 3200, fEnd: 8500, dur: 0.55, gain: 0.06, delay: 0.02 });
    // bright ascending shimmer (the gifts + light)
    [784, 1047, 1319, 1568, 2093].forEach(function (f, i) {
      note({ type: 'sine', f0: f, f1: f * 1.4, dur: 0.24, gain: 0.10, delay: 0.06 + i * 0.05 });
    });
  }

  // "Lights on" — the real audio asset (assets/LighsOn.ogg), played through an
  // <audio> element so it also works on file://. Falls back to a synth swell
  // only if the file can't play.
  var lightsOnEl = null;
  function playLightsOn() {
    if (muted) return;
    try {
      if (!lightsOnEl) {
        lightsOnEl = new Audio('assets/LighsOn.ogg');
        lightsOnEl.preload = 'auto';
      }
      lightsOnEl.volume = sfxLevel();   // ducked while a voice line speaks
      lightsOnEl.currentTime = 0;
      var p = lightsOnEl.play();
      if (p && p.catch) p.catch(function () { synthLightsOn(); });
    } catch (e) { synthLightsOn(); }
  }
  // synth fallback (used only if LighsOn.ogg is unavailable)
  function synthLightsOn() {
    note({ type: 'sine', f0: 220, f1: 660, dur: 0.5, gain: 0.14 });
    note({ type: 'triangle', f0: 330, f1: 880, dur: 0.45, gain: 0.07, delay: 0.02 });
    noise({ filter: 'highpass', fStart: 2600, fEnd: 9000, dur: 0.5, gain: 0.05, delay: 0.04 });
    [880, 1174, 1568].forEach(function (f, i) {
      note({ type: 'sine', f0: f, f1: f * 1.3, dur: 0.3, gain: 0.09, delay: 0.12 + i * 0.06 });
    });
  }

  // Hand-place drop sound (assets/handPlaceSound.ogg). Uses an <audio> element
  // (not fetch/WebAudio) so it plays on file:// too.
  var handPlaceEl = null;
  function playHandPlace() {
    if (muted) return;
    try {
      if (!handPlaceEl) {
        handPlaceEl = new Audio('assets/handPlaceSound.ogg');
        handPlaceEl.preload = 'auto';
      }
      handPlaceEl.volume = sfxLevel();   // ducked while a voice line speaks
      handPlaceEl.currentTime = 0;
      var p = handPlaceEl.play();
      if (p && p.catch) p.catch(function () {});
    } catch (e) { /* no-op */ }
  }

  // Clap/cheer (assets/clapSound.ogg) — played whenever the celebratory
  // successGogo appears.
  var clapEl = null;
  function playClap() {
    if (muted) return;
    try {
      if (!clapEl) {
        clapEl = new Audio('assets/clapSound.ogg');
        clapEl.preload = 'auto';
      }
      clapEl.volume = sfxLevel();   // ducked while a voice line speaks
      clapEl.currentTime = 0;
      var p = clapEl.play();
      if (p && p.catch) p.catch(function () {});
    } catch (e) { /* no-op */ }
  }

  // Looping music bed (audios/Bgm.mp3) — starts on unlock (inside the Play-tap
  // gesture, so autoplay policies allow it) and runs under every screen. The
  // track is mastered hot (0 dB peaks, same mean level as the voice lines), so
  // it sits LOW and drops further while Gogo/Tara speak (see duckSFX).
  var BGM_VOL = 0.15, BGM_DUCK = 0.06;
  var bgmEl = null;
  function playBgm() {
    if (muted) return;
    try {
      if (!bgmEl) {
        bgmEl = new Audio('audios/Bgm.mp3');
        bgmEl.loop = true;
        bgmEl.preload = 'auto';
      }
      bgmEl.volume = voActive() ? BGM_DUCK : BGM_VOL;
      var p = bgmEl.play();
      if (p && p.catch) p.catch(function () { /* blocked: silent until next call */ });
    } catch (e) { /* no-op */ }
  }

  function setMuted(v) {
    muted = !!v;
    if (muted && voCurrent) { voCurrent.pause(); voCurrent.currentTime = 0; }
    if (bgmEl) { if (muted) bgmEl.pause(); else playBgm(); }
  }

  return {
    unlock: unlock,
    playClick: playClick,
    playPop: playPop,
    playHover: playHover,
    playSuccess: playSuccess,
    playWrong: playWrong,
    playWhoosh: playWhoosh,
    playSparkle: playSparkle,
    playDialogue: playDialogue,
    playVO: playVO,
    whenReady: whenReady,
    whenVOIdle: whenVOIdle,
    voDuration: voDuration,
    playBurst: playBurst,
    playHandPlace: playHandPlace,
    playLightsOn: playLightsOn,
    playClap: playClap,
    playBgm: playBgm,
    setMuted: setMuted
  };
})();
